ampel_id: AMPEL-08-SOLAR
description: Solar Powered
trl: 7
status: OPERATIONAL
active_programs:
- Zephyr S
green_potential:
  score: 75
  class: High
  emoji: ♻️
  drivers:
  - zero_emission
  - persistence
  - HAPS
  retrofit_feasibility: Low
  certification_risk: Low
  infrastructure_impact: High
segments:
- ARC-ARCHITECTURE
- MEC-MECHANICAL
