framework:
  name: OPTIM-DT_AMEDEO-PELLICCIA
  version: '7.0'
  generated: 2025-08-25 17:27:29 UTC
segments:
- A-ARCHITECTURE
- M-MECHANICAL
- E-ENVIRONMENTAL
- D-DIGITAL
- E2-ENERGY
ampels: 1
lifecycle_phases:
- 01-CONCEPT
- 02-DESIGN
- 03-DEVELOPMENT
- 04-MANUFACTURING
- 05-TESTING
- 06-CERTIFICATION
- 07-PRODUCTION
- 08-OPERATION
- 09-MAINTENANCE
- 10-UPGRADE
- 11-DISPOSAL
total_cis: 355
