# OPTIM-DT Framework Configuration
framework:
  name: OPTIM-DT_AMEDEO-PELLICCIA
  version: '10.0'  # Latest version
  generated: 2025-08-25 17:27:29 UTC
  
# Core segments (AMEDEO-PELLICCIA)
segments:
  - A-ARCHITECTURE
  - M-MECHANICAL
  - E-ENVIRONMENTAL
  - D-DIGITAL
  - E2-ENERGY
  - O-OPERATIONS
  - P-PROPULSION
  - E3-ELECTRONICS
  - L-LOGISTICS
  - L2-LINKS
  - I-INTEGRATION
  - C-CONTROL
  - C2-CERTIFICATION
  - I2-INTELLIGENCE
  - A2-AIRPORTS

# Lifecycle phases
lifecycle_phases:
  - 01-Requirements
  - 02-Design
  - 03-Building-Prototyping
  - 04-Executables-Packages
  - 05-Verification-Validation
  - 06-Integration-Qualification
  - 07-Certification-Security
  - 08-Production-Scale
  - 09-Ops-Services
  - 10-MRO
  - 11-Sustainment-Recycle

# Generation settings
generation:
  base_path: "OPTIM-COMPLETE-V10"
  ampels: 35
  domains:
    - AIR      # 35 AMPELs
    - SPACE    # 10 AMPELs
    - GROUND   # 10 AMPELs
    - DEFENSE  # 10 AMPELs
    - CROSS    # 10 AMPELs
  total_cis: 355  # Per AMPEL

# Green Framework Configuration (optional)
green_framework:
  enabled: false
  version: "5.0"
  focus: "green_potential"
  base_path: "OPTIM-GREEN"
  max_segments: 5
  cas_per_segment: 2
  cis_per_ca: 2
  top_n_ampels: 10
  
  scoring:
    criteria:
      decarbonization: 0.30
      aerodynamic_efficiency: 0.25
      electrification_potential: 0.20
      operational_leverage: 0.15
      certification_maturity: 0.10
    
    thresholds:
      high: 75
      medium: 60
      low: 0

# Output settings
output_formats:
  - yaml
  - json
  - markdown