ampel_id: AMPEL-27-BW
description: Box Wing
trl: 4
status: RESEARCH
active_programs:
- PrandtlPlane
green_potential:
  score: 73
  class: Medium
  emoji: ♻︎
  drivers:
  - efficiency
  - capacity
  - stability
  retrofit_feasibility: Low
  certification_risk: High
  infrastructure_impact: Medium
segments:
- ARC-ARCHITECTURE
- MEC-MECHANICAL
