ampel_id: AMPEL-05-HYDROGEN-BWB
description: Hydrogen BWB
trl: 5
status: DEVELOPMENT
active_programs:
- Airbus ZEROe BWB
green_potential:
  score: 78
  class: High
  emoji: ♻️
  drivers:
  - zero_emission
  - efficiency
  - volume
  retrofit_feasibility: Low
  certification_risk: High
  infrastructure_impact: High
segments:
- ARC-ARCHITECTURE
- MEC-MECHANICAL
