ampel_id: AMPEL-02-BWB
description: Blended Wing Body
trl: 6
status: DEVELOPMENT
active_programs:
- JetZero
- MAVERIC
green_potential:
  score: 85
  class: High
  emoji: ♻️
  drivers:
  - efficiency
  - hydrogen_volume
  - low_noise
  retrofit_feasibility: Low
  certification_risk: High
  infrastructure_impact: Medium
segments:
- ARC-ARCHITECTURE
- MEC-MECHANICAL
