ampel_id: AMPEL-07-ELECTRIC-ROTARY
description: Electric Rotary Wing
trl: 8
status: DEVELOPMENT
active_programs:
- Joby
- Archer
green_potential:
  score: 76
  class: High
  emoji: ♻️
  drivers:
  - zero_emission_local
  - urban
  - modular
  retrofit_feasibility: High
  certification_risk: Low
  infrastructure_impact: Medium
segments:
- ARC-ARCHITECTURE
- MEC-MECHANICAL
