ampel_id: AMPEL-04-HYDROGEN-TUBE
description: Hydrogen Tube Wing
trl: 5
status: DEVELOPMENT
active_programs:
- ZeroAvia
- Airbus ZEROe
green_potential:
  score: 80
  class: High
  emoji: ♻️
  drivers:
  - zero_emission
  - existing_infra
  - scalability
  retrofit_feasibility: Low
  certification_risk: High
  infrastructure_impact: Medium
segments:
- ARC-ARCHITECTURE
- MEC-MECHANICAL
