ampel_id: AMPEL-06-eSTOL
description: Electric STOL
trl: 5
status: DEVELOPMENT
active_programs:
- Electra.aero
green_potential:
  score: 77
  class: High
  emoji: ♻️
  drivers:
  - electrification
  - short_field
  - quiet
  retrofit_feasibility: Medium
  certification_risk: Medium
  infrastructure_impact: Low
segments:
- ARC-ARCHITECTURE
- MEC-MECHANICAL
